version: '3'


services:
  redis:
    image: "redislabs/redismod:edge"
    ports:
      - "6379:6379"
  application:
    image: "maguec/ai_basket_analysis:latest"
    links:
      - "redis:redis"
    ports:
      - "8080:8080"
    environment:
        - REDIS_SERVER=redis
        - REDIS_PORT=6379
